//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Record
    {
        public int id { get; set; }
        public int id_appointment { get; set; }
        public string reason { get; set; }
        public string prescription { get; set; }
        public string diseases { get; set; }
        public string allergies { get; set; }
        public string medicines { get; set; }
        public string surgeries { get; set; }
        public System.DateTime created_at { get; set; }
        public bool active { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
