//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Queues = new HashSet<Queue>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int id { get; set; }
        public int id_role { get; set; }
        public int id_area { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string photo { get; set; }
        public string email { get; set; }
        public string dni { get; set; }
        public string password { get; set; }
        public string specialization { get; set; }
        public bool active { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<Queue> Queues { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
